import './globals.css'
import type { Metadata } from 'next'
import { NextAuthProvider } from "./providers";

export const metadata: Metadata = {
  title: 'Netflix Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <NextAuthProvider>{children}</NextAuthProvider>
    </body>
    </html>
  )
}
